- command: which gcc-
  register: apache_result 
  ignore_errors: True

- debug: msg="gcc is not. NG"
  when: apache_result|failed
- debug: msg="gcc is exists OK"
  when: apache_result|success

#- command: systemctl graceful httpd
#  when: apache_result|success
#- command: htpasswd -c /etc/nagios/passwd {{nagois_web_user}}
#  when: apache_result|success

