---
- shell: echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
- shell: echo 1 > /proc/sys/net/ipv6/conf/default/disable_ipv6

- shell: grep -e "^vm.swappiness = 0" /etc/sysctl.conf
  ignore_errors: True
  register: is_swappiness
- shell: echo "vm.swappiness = 0" >> /etc/sysctl.conf
  when: is_swappiness|failed

- shell: grep -e "^net.ipv6.conf.all.disable_ipv6 = 1" /etc/sysctl.conf
  ignore_errors: True
  register: disable_ipv6
- shell: echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
  when: disable_ipv6|failed
- shell: /usr/sbin/sysctl -p
